stages:
  - test
  - build
  - retag
  - deploy

include:
  template: SAST.gitlab-ci.yml

variables:
  IMAGE_TAG_FRONTEND: $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_SHA
  IMAGE_TAG_MASTER: $CI_REGISTRY_IMAGE/master:$CI_COMMIT_SHA
  IMAGE_TAG_SLAVE: $CI_REGISTRY_IMAGE/slave:$CI_COMMIT_SHA
  IMAGE_TAG_FRONTEND_STABLE: $CI_REGISTRY_IMAGE/frontend:stable
  IMAGE_TAG_MASTER_STABLE: $CI_REGISTRY_IMAGE/master:stable
  IMAGE_TAG_SLAVE_STABLE: $CI_REGISTRY_IMAGE/slave:stable
  GO111MODULE: "on"
  SCAN_KUBERNETES_MANIFESTS: "true"
  SAST_DISABLE_DIND: "true"
  SAST_DEFAULT_ANALYZERS: "secrets,kubesec,eslint,gosec"

test-master:
  stage: test
  image: golang:1.13
  allow_failure: true
  script:
    - export GO111MODULE=on
    - go test ./loaddriver-master/...

test-slave:
  stage: test
  image: golang:1.13
  allow_failure: true
  script:
    - export GO111MODULE=on
    - go test ./loaddriver-slave/...

build-master:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR/loaddriver-master --dockerfile $CI_PROJECT_DIR/loaddriver-master/Dockerfile --destination $IMAGE_TAG_MASTER --destination $IMAGE_TAG_MASTER:latest

build-slave:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR/loaddriver-slave --dockerfile $CI_PROJECT_DIR/loaddriver-slave/Dockerfile --destination $IMAGE_TAG_SLAVE --destination $IMAGE_TAG_SLAVE:latest

build-frontend:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR/loaddriver-frontend --dockerfile $CI_PROJECT_DIR/loaddriver-frontend/Dockerfile --destination $IMAGE_TAG_FRONTEND --destination $IMAGE_TAG_FRONTEND:latest

retag:
  stage: retag
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  only:
    - master
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - echo "FROM $IMAGE_TAG_FRONTEND" | /kaniko/executor --dockerfile /dev/stdin --destination $IMAGE_TAG_FRONTEND_STABLE
    - echo "FROM $IMAGE_TAG_MASTER" | /kaniko/executor --dockerfile /dev/stdin --destination $IMAGE_TAG_MASTER_STABLE
    - echo "FROM $IMAGE_TAG_SLAVE" | /kaniko/executor --dockerfile /dev/stdin --destination $IMAGE_TAG_SLAVE_STABLE

deploy-prod:
  stage: deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: [""]
  allow_failure: false
  when: manual
  only:
    - master
  script:
    - kubectl -n load-driver set image deployment/loaddriver-frontend app=$IMAGE_TAG_FRONTEND_STABLE --record
    - kubectl -n load-driver set image deployment/loaddriver-master app=$IMAGE_TAG_MASTER_STABLE --record
    - kubectl -n load-driver set image deployment/loaddriver-slave app=$IMAGE_TAG_SLAVE_STABLE --record
