version: "3"
services:
  frontend:
    image: simoneismann/loaddriver-frontend:latest
    environment:
      API_ROOT: "http://localhost:81"
      CONSOLE_URI: "ws://localhost:81/jobs/current/output"
    ports:
      - "80:80"
  master:
    image: simoneismann/loaddriver-master:latest
    ports:
      - "81:80"
  slave:
    image: simoneismann/loaddriver-slave:latest
    environment:
      REGISTRY_HOST: "master"
      REGISTRY_PORT: "80"
    ports:
      - "82:80"
