version: "3"
services:
  master:
    image: simoneismann/loaddriver-master
    ports:
      - "80:80"
  slave:
    image: simoneismann/loaddriver-slave
    environment:
      REGISTRY_HOST: "master"
      REGISTRY_PORT: "80"

networks:
  default:
    external:
      name: load-driver-network