version: "3"
services:
  frontend:
    image: simoneismann/loaddriver-frontend
    environment:
      API_ROOT: "http://localhost:81"
      CONSOLE_URI: "ws://localhost:81/jobs/current/output"
    ports:
      - "80:80"
  master:
    image: simoneismann/loaddriver-master
    ports:
      - "81:80"
  slave:
    image: simoneismann/loaddriver-slave
    environment:
      REGISTRY_HOST: "master"
      REGISTRY_PORT: "80"

networks:
  default:
    external:
      name: load-driver-network
