version: "3"
services:
  registry:
    image: descartesresearch/teastore-registry
    expose:
      - "8080"
  db:
    image: descartesresearch/teastore-db
    expose:
      - "3306"
    ports:
      - "3306:3306"
  persistence:
    image: descartesresearch/teastore-persistence
    expose:
      - "8080"
    environment:
      HOST_NAME: "persistence"
      REGISTRY_HOST: "registry"
      DB_HOST: "db"
      DB_PORT: "3306"
  auth:
    image: descartesresearch/teastore-auth
    expose:
      - "8080"
    environment:
      HOST_NAME: "auth"
      REGISTRY_HOST: "registry"
  image:
    image: descartesresearch/teastore-image
    expose:
      - "8080"
    environment:
      HOST_NAME: "image"
      REGISTRY_HOST: "registry"
  recommender:
    image: descartesresearch/teastore-recommender
    expose:
      - "8080"
    environment:
      HOST_NAME: "recommender"
      REGISTRY_HOST: "registry"
  webui:
    image: descartesresearch/teastore-webui
    expose:
      - "8080"
    environment:
      HOST_NAME: "webui"
      REGISTRY_HOST: "registry"
    ports:
      - "8080:8080"
  frontend:
    image: simoneismann/loaddriver-frontend:latest
    environment:
      API_ROOT: "http://localhost:81"
      CONSOLE_URI: "ws://localhost:81/jobs/current/output"
    ports:
      - "80:80"
  master:
    image: simoneismann/loaddriver-master:latest
    ports:
      - "81:80"
  slave:
    image: simoneismann/loaddriver-slave:latest
    environment:
      REGISTRY_HOST: "master"
      REGISTRY_PORT: "80"
    ports:
      - "82:80"
